# WARNING - Generated by {fusen} from dev/flat_penguins.Rmd: do not edit by hand


test_that("works", {
  expect_true(inherits(table_island, "function"))
  expect_error(table_island(data = palmerpenguins::penguins, island = "XXiasnhg2999"))
})
