# WARNING - Generated by {fusen} from dev/flat_penguins.Rmd: do not edit by hand

#' plot_island Draw a scatter plot for the island.
#' @importFrom hrbrthemes theme_ipsum_rc
#' @importFrom ggplot2 aes ggplot geom_point ggtitle
#' @param data Optional: the datatset used to draw.
#' @param island island's name
#' @export
#' @return A ggplot picture
#' @examples
#' \dontrun{
#'   plot_island(data = palmerpenguins::penguins,
#'               island = "Dream")
#' }


plot_island <- function(data, island) {
  all_island = unique(data$island)
  if (island %in% all_island) {
    data %>% 
      filter(island == island) %>% 
      ggplot(aes(x = bill_length_mm, y = bill_depth_mm, colour = species)) +
      geom_point(size = 3) +
      ggtitle(str_glue("Island: {island}"))
      theme_ipsum_rc()
  } else {
    stop(str_glue("There isn't any island called {island}"))
  }
}
