# WARNING - Generated by {fusen} from dev/flat_penguins.Rmd: do not edit by hand

#' get table by island
#'
#' @return table
#' @export
#' @param data Optional: the dataset to be used
#' @param island which island to glance
#' @importFrom dplyr filter summarise n group_by
#' @importFrom flextable flextable autofit
#' @importFrom stringr str_glue
#' @examples
#' penguins <- palmerpenguins::penguins
#' table_island(data = penguins, island = "Torgersen")
#' table_island(data = penguins, island = "Dream")
table_island <- function(data, island) {
  all_island = unique(data$island)
  if (island %in% all_island) {
    data %>% 
      filter(island == island) %>% 
      group_by(island, species) %>% 
      summarise(N = n(), 
               avg_bill_length = mean(bill_length_mm, na.rm = TRUE),
               avg_bill_depth = mean(bill_depth_mm, na.rm = TRUE)) %>% 
      flextable() %>% 
      autofit()
  } else {
    stop(str_glue("There isn't any island called {island}"))
  }
}
